### ISSUE TITLE
Missing files and bug in parse_rtla

### ISSUE THREAD

**Issue by musamaanjum** [Linaro/test-definitions#530]
I'm running the rtla-timerlat and rtla-osnoise tests. But there are different kinds of errors.
- Some files are missing. Probably rtla needs to generate these files?
- parse_rtla.py is acting up. Maybe some files aren't found or bug in the script itself.

Logs:
```
rtla-timerlat.sh -d 60s -w hackbench
Error enabling osnoise:thread_noise trigger hist:key=cpu,comm,duration.buckets=1000:sort=duration
mv: cannot stat 'osnoise_thread_noise_hist.txt': No such file or directory
mv: cannot stat 'osnoise_irq_noise_hist.txt': No such file or directory
rtla-timerlat pass

rtla-osnoise.sh -d 60s -w hackbench
mv: cannot stat 'osnoise_thread_noise_hist.txt': No such file or directory
mv: cannot stat 'osnoise_irq_noise_hist.txt': No such file or directory
mv: cannot stat 'osnoise_sample_threshold_hist.txt': No such file or directory
Traceback (most recent call last):
  File "/test-definitions/automated/linux/rtla/./parse_rtla.py", line 139, in <module>
    main(parse_args())
  File "/test-definitions/automated/linux/rtla/./parse_rtla.py", line 127, in main
    data = parse_osnoise(infile)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/test-definitions/automated/linux/rtla/./parse_rtla.py", line 87, in parse_osnoise
    data["num_threads"] = num_cols
                          ^^^^^^^^
UnboundLocalError: cannot access local variable 'num_cols' where it is not associated with a value
Traceback (most recent call last):
  File "/test-definitions/automated/linux/rtla/../../lib/parse_rt_tests_results.py", line 87, in <module>
    main()
  File "/test-definitions/automated/linux/rtla/../../lib/parse_rt_tests_results.py", line 83, in main
    parse_json(sys.argv[1], sys.argv[2])
  File "/test-definitions/automated/linux/rtla/../../lib/parse_rt_tests_results.py", line 62, in parse_json
    with open(filename) as file:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/test-definitions/automated/linux/rtla/output/rtla-osnoise.json'
```

**Comment by musamaanjum** [comment]
cc: @igaw

**Comment by igaw** [comment]
For the first problem we need to add `--no-summary`  to the `rtla osnose hist` command. 
Looking into the second problem next.

**Comment by igaw** [comment]
```patch
modified   automated/linux/rtla/parse_rtla.py
@@ -62,6 +62,8 @@ import json
 
     if col[0].endswith(":"):
         name = col[0][:-1]
+        if name == "ALL":
+            return
         hist[i][name] = int(col[sel])
     else:
         hist[i]["histogram"][col[0]] = int(col[sel])
```

**Comment by igaw** [comment]
The osnoise tracer seems not to run on my  TW  kernel (6.10.9-1-default), thus the results file is empty. Thus I only tested #531 with `timerlat`. The good news is even though the results file is empty for `osnoise` the parser doesn't fail over. There are just no results reported. In a way, this a corner case and it works too :)
